name: quant_ai_toolkit_app
description: AI-Powered Quantitative Trading Platform Mobile App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API
  dio: ^5.3.2
  http: ^1.1.0
  web_socket_channel: ^2.4.0

  # Data & Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0

  # Charts & Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.1.44
  fl_chart: ^0.65.0

  # Date & Time
  intl: ^0.18.1
  timeago: ^3.6.0

  # Utils
  uuid: ^4.2.1
  crypto: ^3.0.3
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Biometrics & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0

  # Notifications
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.10

  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8

  # QR Code & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

  # File & Image
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1

  # Social & Sharing
  share_plus: ^7.2.1
  url_launcher: ^6.2.1

  # Testing
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
